
runtime: nodejs14 # or another supported version

instance_class: B2
basic_scaling:
  max_instances: 1
  idle_timeout: 10m

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
